services:
  postgres:
    image: postgres:16
    container_name: collaboard-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: collaboard
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: collaboard
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
